"""Verify the Scorecard against the cohort's own recorded ``total_score``.

This is the Definition-of-Done check for model ① (``docs/task_a_plan.md`` §10): *"Scorecard
reproduces the data's total_score within tolerance on the panel (verified)."*

**What "verified" means here.** The scoring standard is ground truth by definition — the
Scorecard is exact *with respect to the published tables*. This script asks a different and
more useful question: does applying those tables to the panel's recorded item values
reproduce the panel's recorded totals? Where it does not, we characterise why rather than
tuning the engine to match (``AGENTS.md``: report divergence rather than hiding it).

Run::

    python -m analysis.verify_scorecard
"""

from __future__ import annotations

import argparse
from pathlib import Path

import pandas as pd

from analysis.loaders import ITEM_UNITS, measurement_year, panel_long
from analysis.scorecard import score_frame
from aptams.rule_engine.tables import load_scoring_tables

DEFAULT_REPORT = Path("analysis/reports/scorecard_verification.md")

#: A cohort-year whose recorded totals follow a different rule from every other cell. The
#: 2017 intake's second year matches at ~1% while every other (year, grade) cell matches at
#: 79-94%, and its totals carry 0.05 granularity where others are rounded to 0.1. Treated as
#: a policy/standard change for that sitting, not as a defect in the engine. Flagged for
#: mentors (``docs/task_a_plan.md`` §8).
ANOMALOUS_CELL = (2018, "g2")

#: Minimum pile-up on a column's extreme value before we treat it as a winsorisation bound
#: rather than a genuine measurement.
CLIP_PILEUP_MIN = 200


def flag_clipped(long: pd.DataFrame) -> pd.Series:
    """Rows whose item values sit on a winsorisation bound.

    The panel was pre-cleaned before it reached us: each item column has an identical extreme
    shared across sexes and grades, with hundreds or thousands of rows piled on it (1,821 rows
    at exactly 185.0s endurance; 1,573 at exactly 1238ml). Those are not the values the
    recorded total was computed from, so they cannot be expected to reproduce it.
    """
    clipped = pd.Series(False, index=long.index)
    for item in ITEM_UNITS:
        col = long[item]
        for bound in (col.min(), col.max()):
            if (col == bound).sum() > CLIP_PILEUP_MIN:
                clipped |= col == bound
    return clipped


def verify(long: pd.DataFrame | None = None) -> pd.DataFrame:
    """Score the whole panel and attach the comparison columns."""
    long = panel_long() if long is None else long
    tables = load_scoring_tables()
    scored = score_frame(long, tables)

    out = long[["student_id", "sex", "grade", "enrollment_year", "total_score"]].copy()
    out["computed"] = scored["total"]
    out["bonus"] = scored["bonus"]
    out["error"] = out["computed"] - out["total_score"]
    out["abs_error"] = out["error"].abs()
    out["exact"] = out["abs_error"] < 1e-9
    out["clipped"] = flag_clipped(long)
    out["meas_year"] = [
        measurement_year(y, g) for y, g in zip(out["enrollment_year"], out["grade"], strict=True)
    ]
    out["anomalous_cell"] = (out["meas_year"] == ANOMALOUS_CELL[0]) & (
        out["grade"] == ANOMALOUS_CELL[1]
    )
    out["clean"] = ~out["clipped"] & ~out["anomalous_cell"]
    return out


def _tolerance_table(err: pd.Series) -> pd.DataFrame:
    rows = [
        ("exact", 1e-9), ("±0.1", 0.1001), ("±0.5", 0.5001),
        ("±1", 1.0001), ("±2", 2.0001), ("±5", 5.0001),
    ]
    return pd.DataFrame(
        [{"tolerance": label, "share": round(float((err <= t).mean()), 4)} for label, t in rows]
    )


def report(res: pd.DataFrame) -> str:
    """Render the verification report as markdown."""
    clean = res[res["clean"]]
    lines: list[str] = []
    add = lines.append

    add("# Scorecard verification\n")
    add("Generated by `python -m analysis.verify_scorecard`. Model ① against the panel's own\n"
        "`total_score`. The scoring tables are extracted from the official PDF by\n"
        "`analysis/extract_scoring_tables.py`; no threshold is entered by hand.\n")

    add("## Headline\n")
    add(f"- Rows scored: **{len(res):,}** ({res['student_id'].nunique():,} students × 4 years)")
    add(f"- Exact agreement, all rows: **{res['exact'].mean():.1%}**")
    add(f"- Exact agreement, clean rows: **{clean['exact'].mean():.1%}** (n={len(clean):,})")
    add(f"- Within ±1 point, clean rows: **{(clean['abs_error'] <= 1.0001).mean():.1%}**\n")

    add("## What is structurally confirmed\n")
    add("These were identified *from the data*, not assumed:\n")
    add("- **Item weights.** Regressing the recorded total on our per-item scores (OLS, no\n"
        "  intercept, 20k rows) recovers 15/15/20/10/10/20/10 — the PDF's weights — with\n"
        "  R² ≈ 0.99 in every measurement year.")
    add("- **Grade-group mapping.** Scoring g1/g2 on the 大一大二 table and g3/g4 on 大三大四\n"
        "  matches at 0.88/0.70/0.85/0.89; forcing the wrong group collapses agreement to\n"
        "  0.03–0.07. Decisive.")
    add("- **Endurance thresholds.** Reconstructing the implied threshold for each score level\n"
        "  from the data reproduces the PDF's printed values exactly at every level with solid\n"
        "  support (males 大一大二; the same holds for the other three sex × grade-group\n"
        "  tables). Literal thresholds are deliberately not reproduced here — they live only in\n"
        "  the git-ignored `data/scoring_tables/` (see that directory's README).")
    add("- **Total = Σ(score × weight) + 附加分, rounded to 1dp, not capped at 100.** Recorded\n"
        "  totals reach 104.4, and 1dp rounding raises agreement from 78.3% to 83.8%.\n")

    add("## Where it diverges, and why\n")
    add("| Subset | Rows | Exact |")
    add("|---|---:|---:|")
    for label, mask in (
        ("All", pd.Series(True, index=res.index)),
        ("Winsorised values (excluded)", res["clipped"]),
        (f"{ANOMALOUS_CELL[0]} {ANOMALOUS_CELL[1]} cell (excluded)", res["anomalous_cell"]),
        ("Clean", res["clean"]),
    ):
        sub = res[mask]
        if len(sub):
            add(f"| {label} | {len(sub):,} | {sub['exact'].mean():.1%} |")
    add("")
    add("**Winsorisation.** The panel was pre-cleaned before it reached us. Every item column\n"
        "has a shared extreme with an implausible pile-up (1,821 rows at exactly 185.0 s\n"
        "endurance; 1,573 at 1238 ml vital capacity; 1,874 at 6.5 s sprint). The recorded total\n"
        "was computed from the original values, so clipped rows cannot reproduce it. A sibling\n"
        "source file is even named 「初步删掉极值」.\n")
    add(f"**The {ANOMALOUS_CELL[0]}-{ANOMALOUS_CELL[1]} cell.** The 2017 intake's second sitting\n"
        "matches at ~1% while every other (year, grade) cell matches at 79–94%, and its totals\n"
        "carry 0.05 granularity where the rest are rounded to 0.1. This looks like a different\n"
        "scoring policy for that sitting — consistent with the team's own `policy_compare_g1.csv`\n"
        "and `covid_compare_g3.csv`. **Mentor question:** which standard applied in 2018?\n")
    add("**Residual.** BMI in the panel disagrees with weight/height² by >0.5 for ~2% of rows,\n"
        "so the BMI column is itself derived and has drifted. This bounds how exactly any\n"
        "re-derivation can match.\n")

    add("## Tolerance curve (clean rows)\n")
    add(_tolerance_table(clean["abs_error"]).to_markdown(index=False))
    add("")

    add("## Agreement by grade (clean rows)\n")
    by_grade = clean.groupby("grade")["exact"].agg(["mean", "count"]).round(4)
    add(by_grade.to_markdown())
    add("")

    add("## Agreement by measurement year (all rows)\n")
    by_year = res.groupby("meas_year")["exact"].agg(["mean", "count"]).round(4)
    add(by_year.to_markdown())
    add("")

    add("## Reading this honestly\n")
    add("The Scorecard is **exact with respect to the published standard** — that is what makes\n"
        "it usable as ground truth for attribution and counterfactuals. Disagreement with the\n"
        "recorded totals is attributable to upstream data handling (winsorisation, a derived BMI\n"
        "column, one anomalous sitting), not to an approximated threshold. No value in\n"
        "`data/scoring_tables/` was entered by hand.\n")
    return "\n".join(lines)


def main() -> None:
    ap = argparse.ArgumentParser(description="Verify the Scorecard against recorded totals.")
    ap.add_argument("--out", type=Path, default=DEFAULT_REPORT)
    args = ap.parse_args()

    res = verify()
    args.out.parent.mkdir(parents=True, exist_ok=True)
    args.out.write_text(report(res), encoding="utf-8")

    clean = res[res["clean"]]
    print(f"Rows scored           : {len(res):,}")
    print(f"Exact, all rows       : {res['exact'].mean():.4f}")
    print(f"Exact, clean rows     : {clean['exact'].mean():.4f}  (n={len(clean):,})")
    print(f"Within +/-1, clean    : {(clean['abs_error'] <= 1.0001).mean():.4f}")
    print(f"Report written to     : {args.out}")


if __name__ == "__main__":
    main()
