"""The privacy boundary is server-side. Test that it holds at the API layer, not the UI."""

import pytest
from fastapi import HTTPException
from fastapi.testclient import TestClient

from aptams.api.app import app
from aptams.api.auth import assert_teacher_may_read_layer
from aptams.layers import DataLayer

client = TestClient(app)

STUDENT = {"X-Role": "student", "X-Subject-Id": "s1"}
TEACHER = {"X-Role": "teacher", "X-Subject-Id": "t1"}


def test_health_reports_scoring_table_readiness():
    """Health reports whether the blocking input is present, without exposing any of it.

    Both states are legitimate: 'absent' on a fresh clone (the tables are git-ignored and are
    generated by `python -m analysis.extract_scoring_tables`), 'loaded' once they exist. The
    contract is that the endpoint says which, and leaks no threshold either way.
    """
    r = client.get("/health")
    assert r.status_code == 200
    body = r.json()
    assert body["tier"] == "T0"
    status = body["scoring_tables"]
    assert status == "loaded" or status.startswith("absent")

    from aptams.rule_engine.tables import ScoringTablesUnavailable, load_scoring_tables

    try:
        load_scoring_tables()
    except (ScoringTablesUnavailable, FileNotFoundError):
        assert status.startswith("absent")
    else:
        assert status == "loaded"


def test_unauthenticated_is_rejected():
    assert client.get("/student/me/standing").status_code == 401


def test_role_gating_blocks_cross_role_access():
    # A student may not reach teacher endpoints and vice versa.
    assert client.get("/teacher/triage", headers=STUDENT).status_code == 403
    assert client.get("/student/me/standing", headers=TEACHER).status_code == 403


def test_authorized_role_reaches_handler_stub():
    # Correct role passes the gate; handler is a documented 501 at T0 (not 401/403).
    assert client.get("/student/me/standing", headers=STUDENT).status_code == 501
    assert client.get("/teacher/triage", headers=TEACHER).status_code == 501


def test_raw_self_report_layer_is_refused_for_teachers():
    # The chokepoint that any teacher serializer must call.
    assert_teacher_may_read_layer(DataLayer.VERIFIED)  # allowed
    assert_teacher_may_read_layer(DataLayer.MEASURED)  # allowed
    with pytest.raises(HTTPException) as exc:
        assert_teacher_may_read_layer(DataLayer.REPORTED)
    assert exc.value.status_code == 403
